server:
  port: 8080
  error:
    include-stacktrace: never

# VARIABLES
database:
  url: jdbc:mysql://localhost:3306/spring_jwt?createDatabaseIfNotExist=true
  user: user
  password: password

spring:
#DATABASE CONFIG
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${database.url}
    username: ${database.user}
    password: ${database.password}
  flyway:
    locations: "classpath:db/migration/{vendor}"
    url: ${database.url}
    user: ${database.user}
    password: ${database.password}

security:
# JWT
  jwt:
    token:
      secret: secret
      expiration: 3600000

# DOCS
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    path: /api-docs
    groups:
      enabled: true
  group-configs:
  - group: all
    paths-to-match:
    - /**
  - group: auth
    paths-to-match:
    - /auth/**
  - group: example
    paths-to-match:
    - /api/example/**